### ISSUE TITLE
v4 proposal for nuxt-e-commerce

### ISSUE THREAD

**Issue by akaJes** [strapi/starters-and-templates#23]
Hello 

I have some customized code for one-click installation

```
git clone https://github.com/akaJes/nuxt-e-commerce.git
yarn create strapi-starter tester ./nuxt-e-commerce/
```

It possible to add it to the common v4 templates?

Thanks

**Comment by remidej** [comment]
Hello

It's great that you created your own starter! We won't reference it here though. That's because we decided not to maintain Nuxt starters anymore, as they simply weren't used enough.

But your starter should work fine with the create-strapi-starter CLI
