### ISSUE TITLE
nextjs installed and started with error

### ISSUE THREAD

**Issue by jingkang99** [strapi/starters-and-templates#27]
![image](https://user-images.githubusercontent.com/10793075/156669781-11c9bd46-1bfb-44a0-b3a2-3a7bde598055.png)

![image](https://user-images.githubusercontent.com/10793075/156669836-8bfed6f6-683c-440b-ae6a-3b649c9b61a9.png)

**Comment by bankincity** [comment]
same issue

**Comment by krzysztofradomski** [comment]
The svg images don't have a size - that's why the component error. You can confirm this in the admin panel, in the media library.
Here's a quick solution:
<img width="970" alt="image" src="https://user-images.githubusercontent.com/11980348/162837104-f50d574b-0e5a-4a70-b629-23a32645c1dd.png">

**Comment by bankincity** [comment]
> The svg images don't have a size - that's why the component error. You can confirm this in the admin panel, in the media library. Here's a quick solution: `/frontend/components/elements/image.js` <img alt="image" width="970" src="https://user-images.githubusercontent.com/11980348/162837104-f50d574b-0e5a-4a70-b629-23a32645c1dd.png">

it work for me
