### ISSUE TITLE
Strapi Starter Gatsby Blog Frontend won't start ; "gatsby-source-strapi" threw an error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by bast111** [strapi/starters-and-templates#28]
Hi guys, wanted to give it a try with this starter. 
Everything installed properly. Backend started without any problem. 
I then created the API Token in Strapi 
![apiToken](https://user-images.githubusercontent.com/31862563/160014211-6ed86e44-7e30-4754-ae69-6b24c8362eb5.JPG)

Then i added the Token to the .env file 
![envFile](https://user-images.githubusercontent.com/31862563/160015060-dd416e24-9e8f-458c-bd98-fe277e6d190b.JPG)

But then when i start my frontend with gatsby develop it looks like he can't read the strapi nodes and I have this Error, any idea ? :
PS C:\Dev\Projects\gatsby-strapi-blog\frontend> gatsby develop
success compile gatsby files - 1.665s
success load gatsby config - 0.027s
success load plugins - 1.306s
Loaded gatsby-source-strapi-plugin
success onPreInit - 0.008s
success initialize cache - 0.330s
success copy gatsby files - 0.363s
success Compiling Gatsby Functions - 0.414s
success onPreBootstrap - 0.438s
success createSchemaCustomization - 0.013s

 ERROR #11321  PLUGIN

"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

Request failed with status code 403

  Error: Request failed with status code 403

  - createError.js:16 createError
    [frontend]/[axios]/lib/core/createError.js:16:15

  - settle.js:17 settle
    [frontend]/[axios]/lib/core/settle.js:17:12

  - http.js:293 IncomingMessage.handleStreamEnd
    [frontend]/[axios]/lib/adapters/http.js:293:11

  - readable.js:1317 endReadableNT
    internal/streams/readable.js:1317:12

  - task_queues.js:82 processTicksAndRejections
    internal/process/task_queues.js:82:21

warn The gatsby-source-strapi plugin has generated no Gatsby nodes. Do you need it?
success Checking for changed pages - 0.002s
success source and transform nodes - 0.182s
success building schema - 0.234s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allStrapiArticle" on type "Query".

If you don't expect "allStrapiArticle" to exist on the type "Query" it is most likely a typo.
However, if you expect "allStrapiArticle" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development    
server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you  
can query and what shape they have
- You want to optionally use your field "allStrapiArticle" and right now it is not used anywhere. Therefore Gatsby can't infer the type and   
add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned     
"dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-definitions

File: gatsby-node.js:9:24

 ERROR 

There was an error loading your Strapi articles Cannot query field "allStrapiArticle" on type "Query".

  GraphQLError: Cannot query field "allStrapiArticle" on type "Query".

  - graphql-runner.ts:120 GraphQLRunner.validate
    [frontend]/[gatsby]/src/query/graphql-runner.ts:120:16

  - graphql-runner.ts:187 GraphQLRunner.query
    [frontend]/[gatsby]/src/query/graphql-runner.ts:187:39

  - create-graphql-runner.ts:57 apply
    [frontend]/[gatsby]/src/bootstrap/create-graphql-runner.ts:57:8

  - create-pages.ts:34 wrappedGraphQL
    [frontend]/[gatsby]/src/services/create-pages.ts:34:47

  - gatsby-node.js:9 Object.exports.createPages
    C:/Dev/Projects/gatsby-strapi-blog/frontend/gatsby-node.js:9:24

  - api-runner-node.js:462 runAPI
    [frontend]/[gatsby]/src/utils/api-runner-node.js:462:22

  - api-runner-node.js:613 Promise.catch.decorateEvent.pluginName
    [frontend]/[gatsby]/src/utils/api-runner-node.js:613:13

  - debuggability.js:384 Promise._execute
    [frontend]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [frontend]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [frontend]/[bluebird]/js/release/promise.js:103:10

  - api-runner-node.js:611 
    [frontend]/[gatsby]/src/utils/api-runner-node.js:611:16

failed createPages - 0.152s
success createPagesStatefully - 0.096s
info Total nodes: 36, SitePage nodes: 3 (use --verbose for breakdown)
success Checking for changed pages - 0.004s
success write out redirect data - 0.003s
success onPostBootstrap - 0.003s
info bootstrap finished - 9.589s
success onPreExtractQueries - 0.004s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "strapiGlobal" on type "Query".

If you don't expect "strapiGlobal" to exist on the type "Query" it is most likely a typo.
However, if you expect "strapiGlobal" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development    
server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you  
can query and what shape they have
- You want to optionally use your field "strapiGlobal" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned     
"dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-definitions

File: src\components\seo.js:8:7

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "STRAPI_ARTICLE".

GraphQL request:2:27
1 |
2 |   fragment ArticleCard on STRAPI_ARTICLE {
  |                           ^
3 |     id

File: src\pages\index.js:10:27

  GraphQLError: Unknown type "STRAPI_ARTICLE".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allStrapiArticle" on type "Query".

If you don't expect "allStrapiArticle" to exist on the type "Query" it is most likely a typo.
However, if you expect "allStrapiArticle" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development    
server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you  
can query and what shape they have
- You want to optionally use your field "allStrapiArticle" and right now it is not used anywhere. Therefore Gatsby can't infer the type and   
add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned     
"dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-definitions

File: src\pages\index.js:11:7

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "strapiGlobal" on type "Query".

If you don't expect "strapiGlobal" to exist on the type "Query" it is most likely a typo.
However, if you expect "strapiGlobal" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development    
server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you  
can query and what shape they have
- You want to optionally use your field "strapiGlobal" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned     
"dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-definitions

File: src\pages\index.js:16:7

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type
"STRAPI__COMPONENT_SHARED_MEDIASTRAPI__COMPONENT_SHARED_QUOTESTRAPI__COMPONENT_SHARED_RICH_TEXTSTRAPI__COMPONENT_SHARED_SLIDERUnion".

GraphQL request:2:22
2 |   fragment Blocks on STRAPI__COMPONENT_SHARED_MEDIASTRAPI__COMPONENT_SHARED_QUOT
  |                      ^
  | ESTRAPI__COMPONENT_SHARED_RICH_TEXTSTRAPI__COMPONENT_SHARED_SLIDERUnion {

File: src\templates\article-post.js:37:22

  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_MEDIASTRAPI__COMPONENT_SHARED_QUOTESTRAPI__COMPONENT_SHARED_RICH_TEXTSTRAPI__COMPONENT_  SHARED_SLIDERUnion".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "STRAPI__COMPONENT_SHARED_RICH_TEXT".

GraphQL request:4:12
3 |     __typename
4 |     ... on STRAPI__COMPONENT_SHARED_RICH_TEXT {
  |            ^
5 |       richTextBody: body {

File: src\templates\article-post.js:39:12

  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_RICH_TEXT".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "STRAPI__COMPONENT_SHARED_MEDIA".

GraphQL request:15:12
14 |     }
15 |     ... on STRAPI__COMPONENT_SHARED_MEDIA {
   |            ^
16 |       file {

File: src\templates\article-post.js:50:12

  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_MEDIA".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "STRAPI__COMPONENT_SHARED_QUOTE".

GraphQL request:25:12
24 |     }
25 |     ... on STRAPI__COMPONENT_SHARED_QUOTE {
   |            ^
26 |       title

File: src\templates\article-post.js:60:12

  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_QUOTE".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "STRAPI__COMPONENT_SHARED_SLIDER".

GraphQL request:29:12
28 |     }
29 |     ... on STRAPI__COMPONENT_SHARED_SLIDER {
   |            ^
30 |       files {

File: src\templates\article-post.js:64:12

  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_SLIDER".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "strapiArticle" on type "Query".

If you don't expect "strapiArticle" to exist on the type "Query" it is most likely a typo.
However, if you expect "strapiArticle" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development    
server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you  
can query and what shape they have
- You want to optionally use your field "strapiArticle" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add  
it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned     
"dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-definitions

File: src\templates\article-post.js:38:5

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type
"STRAPI__COMPONENT_SHARED_MEDIASTRAPI__COMPONENT_SHARED_QUOTESTRAPI__COMPONENT_SHARED_RICH_TEXTSTRAPI__COMPONENT_SHARED_SLIDERUnion".

GraphQL request:2:22
2 |   fragment Blocks on STRAPI__COMPONENT_SHARED_MEDIASTRAPI__COMPONENT_SHARED_QUOT
  |                      ^
  | ESTRAPI__COMPONENT_SHARED_RICH_TEXTSTRAPI__COMPONENT_SHARED_SLIDERUnion {

File: src\pages\about.js:10:22

  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_MEDIASTRAPI__COMPONENT_SHARED_QUOTESTRAPI__COMPONENT_SHARED_RICH_TEXTSTRAPI__COMPONENT_  SHARED_SLIDERUnion".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "STRAPI__COMPONENT_SHARED_RICH_TEXT".

GraphQL request:4:12
3 |     __typename
4 |     ... on STRAPI__COMPONENT_SHARED_RICH_TEXT {
  |            ^
5 |       richTextBody: body {

File: src\pages\about.js:12:12

  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_RICH_TEXT".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "STRAPI__COMPONENT_SHARED_MEDIA".

GraphQL request:15:12
14 |     }
15 |     ... on STRAPI__COMPONENT_SHARED_MEDIA {
   |            ^
16 |       file {

File: src\pages\about.js:23:12

  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_MEDIA".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "STRAPI__COMPONENT_SHARED_QUOTE".

GraphQL request:25:12
24 |     }
25 |     ... on STRAPI__COMPONENT_SHARED_QUOTE {
   |            ^
26 |       title

File: src\pages\about.js:33:12

  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_QUOTE".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "STRAPI__COMPONENT_SHARED_SLIDER".

GraphQL request:29:12
28 |     }
29 |     ... on STRAPI__COMPONENT_SHARED_SLIDER {
   |            ^
30 |       files {

File: src\pages\about.js:37:12

  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_SLIDER".

  - query-compiler.js:365 processDefinitions
    [frontend]/[gatsby]/src/query/query-compiler.js:365:20

  - query-compiler.js:176 processQueries
    [frontend]/[gatsby]/src/query/query-compiler.js:176:10

  - query-compiler.js:78 compile
    [frontend]/[gatsby]/src/query/query-compiler.js:78:19

  - query-watcher.ts:223 updateStateAndRunQueries
    [frontend]/[gatsby]/src/query/query-watcher.ts:223:40

  - extract-queries.ts:18 extractQueries
    [frontend]/[gatsby]/src/services/extract-queries.ts:18:3

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "strapiAbout" on type "Query".

If you don't expect "strapiAbout" to exist on the type "Query" it is most likely a typo.
However, if you expect "strapiAbout" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development    
server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you  
can query and what shape they have
- You want to optionally use your field "strapiAbout" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it 
to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned     
"dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-definitions

File: src\pages\about.js:11:7

failed extract queries from components - 2.184s
success write out requires - 0.051s
success run page queries - 0.028s - 1/1 35.16/s

 ERROR 

Module not found: Error: Can't resolve '../../public/page-data/sq/d/4175596634.json' in
'C:\Dev\Projects\gatsby-strapi-blog\frontend\src\components'

  ModuleNotFoundError: Module not found: Error: Can't resolve '../../public/page-data/sq/d/4175596634.json' in 'C:\Dev\Projects\gatsby-strapi-  blog\frontend\src\components'

  - Compilation.js:2015 
    [frontend]/[webpack]/lib/Compilation.js:2015:28

  - NormalModuleFactory.js:798 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:798:13

  - NormalModuleFactory.js:270 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:270:22

  - NormalModuleFactory.js:434 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:434:22

  - NormalModuleFactory.js:116 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:116:11

  - NormalModuleFactory.js:670 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:670:25

  - NormalModuleFactory.js:855 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:855:8

  - NormalModuleFactory.js:975 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:975:5

  - async.js:6883 
    [frontend]/[neo-async]/async.js:6883:13

  - NormalModuleFactory.js:950 Array.<anonymous>
    [frontend]/[webpack]/lib/NormalModuleFactory.js:950:14

  - async.js:2517 arrayEachFunc
    [frontend]/[neo-async]/async.js:2517:19

  - async.js:6858 Object.parallel
    [frontend]/[neo-async]/async.js:6858:9

  - NormalModuleFactory.js:873 NormalModuleFactory._resolveResourceErrorHints
    [frontend]/[webpack]/lib/NormalModuleFactory.js:873:12

  - NormalModuleFactory.js:834 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:834:18

 ERROR 

Module not found: Error: Can't resolve '../../public/page-data/sq/d/3105690032.json' in
'C:\Dev\Projects\gatsby-strapi-blog\frontend\src\pages'

  ModuleNotFoundError: Module not found: Error: Can't resolve '../../public/page-data/sq/d/3105690032.json' in 'C:\Dev\Projects\gatsby-strapi-  blog\frontend\src\pages'

  - Compilation.js:2015 
    [frontend]/[webpack]/lib/Compilation.js:2015:28

  - NormalModuleFactory.js:798 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:798:13

  - NormalModuleFactory.js:270 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:270:22

  - NormalModuleFactory.js:434 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:434:22

  - NormalModuleFactory.js:116 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:116:11

  - NormalModuleFactory.js:670 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:670:25

  - NormalModuleFactory.js:855 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:855:8

  - NormalModuleFactory.js:975 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:975:5

  - async.js:6883 
    [frontend]/[neo-async]/async.js:6883:13

  - NormalModuleFactory.js:950 Array.<anonymous>
    [frontend]/[webpack]/lib/NormalModuleFactory.js:950:14

  - async.js:2517 arrayEachFunc
    [frontend]/[neo-async]/async.js:2517:19

  - async.js:6858 Object.parallel
    [frontend]/[neo-async]/async.js:6858:9

  - NormalModuleFactory.js:873 NormalModuleFactory._resolveResourceErrorHints
    [frontend]/[webpack]/lib/NormalModuleFactory.js:873:12

  - NormalModuleFactory.js:834 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:834:18

 ERROR 

Module not found: Error: Can't resolve '../../public/page-data/sq/d/960431041.json' in 'C:\Dev\Projects\gatsby-strapi-blog\frontend\src\pages'

  ModuleNotFoundError: Module not found: Error: Can't resolve '../../public/page-data/sq/d/960431041.json' in 'C:\Dev\Projects\gatsby-strapi-b  log\frontend\src\pages'

  - Compilation.js:2015 
    [frontend]/[webpack]/lib/Compilation.js:2015:28

  - NormalModuleFactory.js:798 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:798:13

  - NormalModuleFactory.js:270 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:270:22

  - NormalModuleFactory.js:434 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:434:22

  - NormalModuleFactory.js:116 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:116:11

  - NormalModuleFactory.js:670 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:670:25

  - NormalModuleFactory.js:855 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:855:8

  - NormalModuleFactory.js:975 
    [frontend]/[webpack]/lib/NormalModuleFactory.js:975:5

  - async.js:6883 
    [frontend]/[neo-async]/async.js:6883:13

  - NormalModuleFactory.js:950 Array.<anonymous>
    [frontend]/[webpack]/lib/NormalModuleFactory.js:950:14

  - async.js:2517 arrayEachFunc
    [frontend]/[neo-async]/async.js:2517:19

  - async.js:6858 Object.parallel
    [frontend]/[neo-async]/async.js:6858:9

  - NormalModuleFactory.js:873 NormalModuleFactory._resolveResourceErrorHints
    [frontend]/[webpack]/lib/NormalModuleFactory.js:873:12

  - NormalModuleFactory.js:834
    [frontend]/[webpack]/lib/NormalModuleFactory.js:834:18

not finished Building development bundle - 2.049s

**Comment by bast111** [comment]
So after looking around a bit more looks like this workaround make it work

```
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `http://localhost:1337`,
        collectionTypes: [
          {
            name: `categories`,
            endpoint: "api/categories",
          }, //Repeat for each of your collection types
        ],
      },
    },
  ],
}
```

**Comment by remidej** [comment]
Hello @bast111, please don't use that workaround, it's not how this source plugin was meant to be used.

Your problem is that Strapi sends a 403 for your requests, which likely means that your API token wasn't passed.

I supposed you didn't change this part of the gatsby config:

```js
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
})
```

In development it will look for a `.env.development`. So try renaming your `.env` file to `.env.development`.

Let me know if that doesn't fix it and I'll reopen

**Comment by bast111** [comment]
Hi Remi thanks for the quick answer.
So i took of all the endpoints from the workaround and created a .env.development file with the Token. And it resolved the 403 error. And now is a 404 error ^^' 
The server is starting at least but : 
```
PS C:\Dev\Projects\gatsby-strapi-blog\frontend> gatsby develop
success compile gatsby files - 4.290s
success load gatsby config - 0.039s
success load plugins - 2.152s
Loaded gatsby-source-strapi-plugin
success onPreInit - 0.008s
success initialize cache - 0.041s
success copy gatsby files - 0.360s
success Compiling Gatsby Functions - 0.544s
success onPreBootstrap - 0.583s
success createSchemaCustomization - 0.016s

 ERROR #11321  PLUGIN

"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

Request failed with status code 404



  Error: Request failed with status code 404

  - createError.js:16 createError
    [frontend]/[axios]/lib/core/createError.js:16:15

  - settle.js:17 settle
    [frontend]/[axios]/lib/core/settle.js:17:12

  - http.js:293 IncomingMessage.handleStreamEnd
    [frontend]/[axios]/lib/adapters/http.js:293:11

  - readable.js:1317 endReadableNT
    internal/streams/readable.js:1317:12

  - task_queues.js:82 processTicksAndRejections
    internal/process/task_queues.js:82:21


warn The gatsby-source-strapi plugin has generated no Gatsby nodes. Do you need it?
success Checking for changed pages - 0.004s
success source and transform nodes - 0.256s
success building schema - 0.373s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allStrapiArticle" on type "Query".

If you don't expect "allStrapiArticle" to exist on the type "Query" it is most likely a typo.
However, if you expect "allStrapiArticle" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development    
server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you  
can query and what shape they have
- You want to optionally use your field "allStrapiArticle" and right now it is not used anywhere. Therefore Gatsby can't infer the type and   
add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned     
"dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-definitions

File: gatsby-node.js:9:24


 ERROR 

There was an error loading your Strapi articles Cannot query field "allStrapiArticle" on type "Query".



  GraphQLError: Cannot query field "allStrapiArticle" on type "Query".
```
![image](https://user-images.githubusercontent.com/31862563/160086527-ad92a5ca-31ed-4c4d-a1af-08664a016e29.png)

**Comment by remidej** [comment]
Can you share your gatsby config?

**Comment by Zara603** [comment]
> Hello @bast111, please don't use that workaround, it's not how this source plugin was meant to be used.
> 
> Your problem is that Strapi sends a 403 for your requests, which likely means that your API token wasn't passed.
> 
> I supposed you didn't change this part of the gatsby config:
> 
> ```js
> require("dotenv").config({
>   path: `.env.${process.env.NODE_ENV}`,
> })
> ```
> 
> In development it will look for a `.env.development`. So try renaming your `.env` file to `.env.development`.
> 
> Let me know if that doesn't fix it and I'll reopen

This is not in documentation
