### ISSUE TITLE
Installation failing with node v17

### ISSUE THREAD

**Issue by pbartusch** [strapi/starters-and-templates#31]
Hi, I got the following error when installing the Starter:

```
npx create-strapi-starter my-project gatsby-blog
```

Resulting in:

```
Error while installing dependencies:
error backend@0.1.0: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "17.3.0"
error Found incompatible module.
```

Seems like the Starter is not compatible with node > 16. Maybe it would help to provide a `Dockerfile` with the suitable environment.

Environment: Apple Silicone M1

**Comment by remidej** [comment]
Hello, this is expected as Strapi only supports the Node LTS versions (even numbers), as mentioned [there](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/cli.html#preparing-the-installation).

I you want to use a non-LTS version on your machine, you can use a Node version manager like [nvm](https://github.com/nvm-sh/nvm#node-version-manager---) or [n](https://github.com/tj/n#n--interactively-manage-your-nodejs-versions) to use Node 14 on your Strapi projects.
