### ISSUE TITLE
Create New Custom Page but no data 

### ISSUE THREAD

**Issue by bankincity** [strapi/starters-and-templates#36]
Please let me know. how to fix it.

    I need to new page for Register Form. 

**Error** : _TypeError: Cannot read properties of undefined (reading 'submitCampaign')_
![image](https://user-images.githubusercontent.com/30035645/163422217-fe808637-061a-42ad-a66e-41a4c50f19f7.png)

url : localhost:3000/campaign

Font-end
`import { useState } from "react";
import { fetchAPI } from "utils/api";
import * as yup from "yup";
import { Formik, Form, Field} from "formik";
import Button from "../elements/button";

const Campaign = ({ data }) => {
  const [loading, setLoading] = useState(false);
  const CampaignSchema = yup.object().shape({

  })   

  return (
      
    <Formik
      initialValues={{ email: "" }}
      validationSchema={CampaignSchema}
      onSubmit={async (values, { setSubmitting, setErrors }) => {
        setLoading(true);
       
      }}
    >
      {({ errors, touched, isSubmitting, data }) => (
        <div>
          <Form className="flex flex-col md:flex-row gap-4">

          <label htmlFor="preName">Pre Name</label> 
            <Field as="select" name="prename">
              <option value="Mr">Mr</option>
              <option value="Miss">Miss</option>
              <option value="Ms">Ms</option>              
            </Field>

          <label htmlFor="firstName">First Name</label>
            <Field
              className="text-base focus:outline-none py-4 md:py-0 px-4 border-2 rounded-md"              
              name="firstname"
            /> 

            <label htmlFor="lastName">Last Name</label>
            <Field
              className="text-base focus:outline-none py-4 md:py-0 px-4 border-2 rounded-md"              
              name="lastname"           
            />        
  
            <Button
              type="submit"
              button={data.submitCampaign}
              disabled={isSubmitting}
              loading={loading}
            />
            
          </Form>
          <p className="text-red-500 h-12 text-sm mt-1 ml-2 text-left">
            {(errors.email && touched.email && errors.email) || errors.api}
          </p>
        </div>
      )}
    </Formik>
  ); 
};

export default Campaign;
`
setting in section.js
![image](https://user-images.githubusercontent.com/30035645/163423064-b49f2a4c-3489-4f2c-a64b-43f868f50350.png)

Back-end (Strapi)
<img width="959" alt="image" src="https://user-images.githubusercontent.com/30035645/163422635-40ef2109-837a-4aaf-818f-c7e15330512a.png">

**Comment by remidej** [comment]
Hello, it looks like this is not an issue with the starter itself, but with your own customizations of the site.

For this kind of help, you can post a message on [our Discord server](https://discord.com/invite/strapi) instead
