### ISSUE TITLE
Relations in Database

### ISSUE THREAD

**Issue by raylud** [strapi/starters-and-templates#40]
It seems your default db implementation for relations in a custom collection is an association table. I would like to have an option to implement by foreign key directly. Is that a possibility or can you suggest a workaround? Thanks.

**Comment by remidej** [comment]
Hello, I think this is not related to starters and templates. It sounds like what you want is more of a Strapi feature, so you can post it on our [feedback portal ](https://github.com/strapi/strapi/issues/new/choose)if you want instead
