### ISSUE TITLE
How to add multiple tags in a single blog

### ISSUE THREAD

**Issue by Shivraj97** [strapi/starters-and-templates#50]
Hello Strapi, I am really sorry to put this as an issue. I have posted it in [Stackoverflow](https://stackoverflow.com/questions/72944888/how-to-add-tags-to-a-blog-and-categorize-them-using-next-js-and-strapi) also. Actually I want to implement something and not able to figure it out so I am posting it here for some help. 
In the Next + Strapi there is an option to categorize blogs based on category however I would like to add multiple tags to a single blog and in my Next app I would like to categorize them based on these tags and View all. I have create a Tag collection type and tried to establish a relation however I am not getting it in API response. Do I need to modify something related to API call in my Next app.
<img width="832" alt="image" src="https://user-images.githubusercontent.com/43899907/178421457-862dac6c-c8dc-49d9-bdbc-065252c08b3c.png">

<img width="832" alt="image" src="https://user-images.githubusercontent.com/43899907/178421512-f5d915a5-caa1-4a4b-a86d-dcdc4f686d5d.png">

<img width="221" alt="image" src="https://user-images.githubusercontent.com/43899907/178422028-1bfc5715-ba83-41ab-990b-3b218f6059a9.png">

**Comment by remidej** [comment]
Hello, I'm closing this as this is not an issue with the starter itself. But I think the issue may come from the permissions. You can check if the Tag collection type has the "find" action enabled for the public route
