### ISSUE TITLE
Are the starters working with V4 ? (problem with at least next-corporate)

### ISSUE THREAD

**Issue by jeromelaurens** [strapi/starters-and-templates#6]
### Describe the bug

The next-corporate starter does not work : 
1. Error on start
2. Error on http://localhost:3000

### Steps to reproduce the behavior

1. create project with starter `yarn create strapi-starter my-project next-corporate`
2. error in logs : `TypeError: Cannot destructure property 'attributes' of 'strapi.getModel(...)' as it is undefined. ...`
3. go to admin and create first login/password
4. go to to http://localhost:3000
5. here is a nice error see ![screenshot](https://user-images.githubusercontent.com/2656354/144624008-afce8089-f377-42d3-885a-024c14ea4968.png)

### Expected behavior
starter to work without error in log or in front

### System

- Node.js version: LTS 16
- yarn
- Strapi version: 4
- Database:
- Operating system: MacOS Monterey

.

**Comment by remidej** [comment]
Thank you for your report. This bug was fixed last week, you should be able to create your starter with the same command now

**Comment by jeromelaurens** [comment]
Thanksa lot, 
it's better now, I don't have anymore the error on http://localhost:3000
But the error in the logs remains
