### ISSUE TITLE
V4 ecommerce starter fails on install

### ISSUE THREAD

**Issue by myrddral** [strapi/starters-and-templates#7]
### Describe the bug

When I run the command
**npx create-strapi-starter my-project next-ecommerce** or **yarn create strapi-starter my-project next-ecommerce**

I get the following error:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getPackageInfo (C:\Users\pc\AppData\Local\npm-cache\_npx\ecd569b0a81a6814\node_modules\create-strapi-starter\utils\fetch-npm-starter.js:19:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getStarterInfo (C:\Users\pc\AppData\Local\npm-cache\_npx\ecd569b0a81a6814\node_modules\create-strapi-starter\utils\build-starter.js:109:26)
    at async buildStarter (C:\Users\pc\AppData\Local\npm-cache\_npx\ecd569b0a81a6814\node_modules\create-strapi-starter\utils\build-starter.js:133:7)
```

On a side note, the blog starter installs and runs nicely.

### Steps to reproduce the behavior

1. try to install the ecommerce starter with npx or yarn
2. Coose "Quickstart" or "Custom"
3. See error in console

### Expected behavior

The ecommerce starter installs without errors.

### System

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: v4
- Database: n/a
- Operating system: Windows 11

**Comment by crtormen** [comment]
> I also have this same output...
> 
> tried multiple starters in node v.12 to v.16, npm v6 to v8, windows 10 and ubuntu 18 with similar results.
> 
> installing v3 with "npm i -g create-strapi-starter@3" and running without npx fixed the issue for me.

Same happening here.
Tried the solution described above by logical-potato, but didn't work either.

**Comment by alanapapa** [comment]
```
rm /usr/local/bin/create-strapi-starter

sudo npm i -g create-strapi-starter@3

npx create-strapi-starter <projectName> <templateName>
```

**Comment by crtormen** [comment]
> ```
> rm /usr/local/bin/create-strapi-starter
> 
> sudo npm i -g create-strapi-starter@3
> 
> npx create-strapi-starter <projectName> <templateName>
> ```

This worked for me. Thank you.

**Comment by orozot** [comment]
I have the same problem in `npx` and `yarn`.

```bash
yarn create strapi-starter my-project https://github.com/strapi/strapi-template-portfolio                                                                                         16:56:16 
yarn create v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-strapi-starter@4.0.2" with binaries:
      - create-strapi-starter
? Choose your installation type Quickstart (recommended)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getPackageInfo (/Users/zhitongren/.config/yarn/global/node_modules/create-strapi-starter/utils/fetch-npm-starter.js:19:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getStarterInfo (/Users/zhitongren/.config/yarn/global/node_modules/create-strapi-starter/utils/build-starter.js:109:26)
    at async buildStarter (/Users/zhitongren/.config/yarn/global/node_modules/create-strapi-starter/utils/build-starter.js:133:7)
```

```bash
npx create-strapi-starter my-project gridsome-portfolio                                                                                                                          16:41:36 
? Choose your installation type Quickstart (recommended)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getPackageInfo (/Users/zhitongren/.npm/_npx/96444/lib/node_modules/create-strapi-starter/utils/fetch-npm-starter.js:19:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getStarterInfo (/Users/zhitongren/.npm/_npx/96444/lib/node_modules/create-strapi-starter/utils/build-starter.js:109:26)
    at async buildStarter (/Users/zhitongren/.npm/_npx/96444/lib/node_modules/create-strapi-starter/utils/build-starter.js:133:7)
```

**Comment by anarayn** [comment]
Any solution for this, I am also facing the same problem.

**Comment by go-fish-wxy** [comment]
> I also have this same output...
> 
> tried multiple starters in node v.12 to v.16, npm v6 to v8, windows 10 and ubuntu 18 with similar results.
> 
> installing v3 with "npm i -g create-strapi-starter@3" and running without npx fixed the issue for me.

That does wonder. 
Work for me & thank you very much

**Comment by dellysoul** [comment]
> I also have this same output...
> 
> tried multiple starters in node v.12 to v.16, npm v6 to v8, windows 10 and ubuntu 18 with similar results.
> 
> installing v3 with "npm i -g create-strapi-starter@3" and running without npx fixed the issue for me.

This also solved it for me

**Comment by tfdbloom** [comment]
That solves it with v3. What should we do if we want starters with v4?

**Comment by QusaiSabri** [comment]
> ```
> rm /usr/local/bin/create-strapi-starter
> 
> sudo npm i -g create-strapi-starter@3
> 
> npx create-strapi-starter <projectName> <templateName>
> ```

This worked for me! Thank you!

**Comment by remidej** [comment]
We decided not to port the ecommerce starter to v4, because it wasn't used enough. Here is what you could do:

- Use the v3 version: `npx create-strapi-starter@3 <projectName> <templateName>`
- Create a v4 port of the ecommerce starter yourself, and publish it on npm

**Comment by Ronyo** [comment]
> We decided not to port the ecommerce starter to v4, because it wasn't used enough. Here is what you could do:
> 
>     * Use the v3 version: `npx create-strapi-starter@3 <projectName> <templateName>`
> 
>     * Create a v4 port of the ecommerce starter yourself, and publish it on npm

That's nice and sweet but templates don't work with v3 strapi anymore. Blog template for sure but it seems that ecommerce also. 
Reference:
https://github.com/strapi/strapi-starter-gatsby-blog/issues/34
https://github.com/strapi/strapi-starter-next-ecommerce/issues/21

**Comment by webhype** [comment]
> We decided not to port the ecommerce starter to v4, because it wasn't used enough. Here is what you could do:

Hard to understand why the one-time effort of porting all starters to v4 isn't undertaken, as it is Strapi's best form of marketing. It's a chicken-and-egg justification: Maybe nobody wants to use Strapi v4 for e-commerce because there's no starter that makes it easy? If I were Strapi, I would invest into 10 starters for a wide range of applications, to showcase the versatility of my platform.
